### ISSUE TITLE
schedules

### ISSUE THREAD

**Issue by itsalb3rt** [Cowofi/cowofi#17]
**Description**

Allow auth users to create schedule in spaces

**Todo**

- [x] Create form into spaces details
    - [x] Validate the active week days with the available days selected by the space owner
    - [x] Validate the active time with the opens and closes times selected by the space owner
- [x] #22
- [x] Show all schedules into the user profile
    - [x] Show all my schedules
    - [x] Show all my spaces schedules
- [x] Spaces owners can accept or reject any schedules

**Comment by itsalb3rt** [comment]
Ready, now the #47 issue is ready to working

**Comment by itsalb3rt** [comment]
Ready!
