### ISSUE TITLE
Space reviews

### ISSUE THREAD

**Issue by itsalb3rt** [Cowofi/cowofi#47]
**Description**

Handle the spaces reviews with stars, and optionally a comment.

**Demo**

![Image](https://user-images.githubusercontent.com/35310226/190285403-b00e0cd2-0ead-4b7a-a3b0-6659fd2b1fee.png)

and after add the reviews into the spaces

![Image](https://user-images.githubusercontent.com/35310226/190285450-33f94fda-626f-47ef-9b98-6c8f21bf60f6.png)

## To-Do

- [x] Create form component
- [x] Create component to show the review (user first name, stars, and comments
- [x] Show all the reviews of spaces in the space details
- [x] Create action to check if the logged user have a pending review when he enters to any space
- [ ] Created a section into the user profile to get all the pending reviews of the logged user

**Comment by itsalb3rt** [comment]
Block by the #17 _(Spaces owners can accept or reject any schedules)_
